---
- hosts: ws
  become: True
  ignore_errors: yes
  gather_facts: yes
  become_user: root
  vars_files:
     - vars.yml

  tasks:
    - name: download a file from github
      get_url:
        url: "{{ LINK_URL }}"
        dest: "{{ DESTINATION }}"
        mode: '0644'

    - name: delete a file from /tmp
      file:
        path: "{{ DESTINATION }}"
        state: absent