---
- hosts: ws
  become: True
  ignore_errors: yes
  gather_facts: yes
  become_user: root

  vars:
    f_name: John

  tasks:
    - name: Debug module
      debug:
       # msg: "hello from my playbook" 
        var: f_name  

    - name: check server uptime
      command: uptime
      register: uptime_output

    - name: Display output variable
      debug:
        var: uptime_output.stdout